# Generated by Django 5.1.1 on 2024-10-01 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilatesapp', '0002_delete_inasistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fecha',
        ),
        migrations.AddField(
            model_name='turno',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], default='Lunes', max_length=9),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
    ]
